# Generated by Django 6.1.1 on 2026-09-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_exercise_completed_alter_exercise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='day',
            field=models.CharField(default='Monday', max_length=20),
        ),
    ]
